In [24]:
l = [[(0, n) for n in range(5)], [(4, n) for n in range(5)], [(n, 0) for n in range(5)], [(n, 4) for n in range(5)]]
l

[[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4)],
 [(4, 0), (4, 1), (4, 2), (4, 3), (4, 4)],
 [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0)],
 [(0, 4), (1, 4), (2, 4), (3, 4), (4, 4)]]

In [25]:
from enum import Enum

class Move(Enum):
    TOP = 0
    BOTTOM = 1
    LEFT = 2
    RIGHT = 3

l1 = []
for n in range(5):
    for m in [Move.TOP, Move.BOTTOM, Move.LEFT, Move.RIGHT]:
        l1.append(((0, n), m))
        l1.append(((4, n), m))
        l1.append(((n, 0), m))
        l1.append(((n, 4), m))

l1 = list(set(l1))

In [26]:
import numpy as np
from game import Game, Move, Player
from copy import deepcopy

g = Game(np.ones((5, 5), dtype=np.uint8) * -1)
# print(g._board)
moves_list = []
for n in range(5):
    for m in [Move.TOP, Move.BOTTOM, Move.LEFT, Move.RIGHT]:
        moves_list.append(((0, n), m))
        moves_list.append(((4, n), m))
        moves_list.append(((n, 0), m))
        moves_list.append(((n, 4), m))
moves_list = sorted(list(set(moves_list)), key=lambda e: e[0])  # every element is ((x, y), direction)

acceptable = []
not_acceptable = []

for move in moves_list:
    copyboard = deepcopy(g)
    ok = copyboard.move(move[0], move[1], 0)
    if ok:
        acceptable.append(move)
        print(f"{move} => \n {copyboard._board}")
    else:
        not_acceptable.append(move)
print(len(acceptable))
print(len(not_acceptable))


((0, 0), <Move.RIGHT: 3>) => 
 [[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]]
((0, 0), <Move.BOTTOM: 1>) => 
 [[-1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 1), <Move.LEFT: 2>) => 
 [[-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 1), <Move.RIGHT: 3>) => 
 [[-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 1), <Move.BOTTOM: 1>) => 
 [[-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 2), <Move.RIGHT: 3>) => 
 [[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 2), <Move.BOTTOM: 1>) => 
 [[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 2), <Move.LEFT: 2>) => 
 [[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
((0, 3), <Move.LEFT: 2>

In [27]:
acceptable

[((0, 0), <Move.RIGHT: 3>),
 ((0, 0), <Move.BOTTOM: 1>),
 ((0, 1), <Move.LEFT: 2>),
 ((0, 1), <Move.RIGHT: 3>),
 ((0, 1), <Move.BOTTOM: 1>),
 ((0, 2), <Move.RIGHT: 3>),
 ((0, 2), <Move.BOTTOM: 1>),
 ((0, 2), <Move.LEFT: 2>),
 ((0, 3), <Move.LEFT: 2>),
 ((0, 3), <Move.RIGHT: 3>),
 ((0, 3), <Move.BOTTOM: 1>),
 ((0, 4), <Move.RIGHT: 3>),
 ((0, 4), <Move.TOP: 0>),
 ((1, 0), <Move.LEFT: 2>),
 ((1, 0), <Move.RIGHT: 3>),
 ((1, 0), <Move.BOTTOM: 1>),
 ((1, 0), <Move.TOP: 0>),
 ((2, 0), <Move.RIGHT: 3>),
 ((2, 0), <Move.BOTTOM: 1>),
 ((2, 0), <Move.TOP: 0>),
 ((2, 0), <Move.LEFT: 2>),
 ((3, 0), <Move.TOP: 0>),
 ((3, 0), <Move.LEFT: 2>),
 ((3, 0), <Move.RIGHT: 3>),
 ((3, 0), <Move.BOTTOM: 1>),
 ((4, 0), <Move.LEFT: 2>),
 ((4, 0), <Move.BOTTOM: 1>),
 ((4, 1), <Move.TOP: 0>),
 ((4, 1), <Move.LEFT: 2>),
 ((4, 1), <Move.RIGHT: 3>),
 ((4, 2), <Move.TOP: 0>),
 ((4, 2), <Move.LEFT: 2>),
 ((4, 2), <Move.RIGHT: 3>),
 ((4, 3), <Move.TOP: 0>),
 ((4, 3), <Move.LEFT: 2>),
 ((4, 3), <Move.RIGHT: 3>),
 ((4, 4)

In [28]:
not_acceptable

[((0, 0), <Move.TOP: 0>),
 ((0, 0), <Move.LEFT: 2>),
 ((0, 1), <Move.TOP: 0>),
 ((0, 2), <Move.TOP: 0>),
 ((0, 3), <Move.TOP: 0>),
 ((0, 4), <Move.LEFT: 2>),
 ((0, 4), <Move.BOTTOM: 1>),
 ((1, 4), <Move.BOTTOM: 1>),
 ((1, 4), <Move.TOP: 0>),
 ((1, 4), <Move.LEFT: 2>),
 ((1, 4), <Move.RIGHT: 3>),
 ((2, 4), <Move.BOTTOM: 1>),
 ((2, 4), <Move.TOP: 0>),
 ((2, 4), <Move.LEFT: 2>),
 ((2, 4), <Move.RIGHT: 3>),
 ((3, 4), <Move.LEFT: 2>),
 ((3, 4), <Move.RIGHT: 3>),
 ((3, 4), <Move.BOTTOM: 1>),
 ((3, 4), <Move.TOP: 0>),
 ((4, 0), <Move.RIGHT: 3>),
 ((4, 0), <Move.TOP: 0>),
 ((4, 1), <Move.BOTTOM: 1>),
 ((4, 2), <Move.BOTTOM: 1>),
 ((4, 3), <Move.BOTTOM: 1>),
 ((4, 4), <Move.BOTTOM: 1>),
 ((4, 4), <Move.RIGHT: 3>)]

In [32]:
matrix = np.ones((5, 5), dtype=np.uint8) * -1
matrix[( 1,0)] = 3
print(matrix)

[[-1 -1 -1 -1 -1]
 [ 3 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
